p8105_hw1_fir2103
================
Farizah Rob
2022-09-24

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

### Problem 1

``` r
data("penguins", package = "palmerpenguins")
```

Exploring the data

``` r
names(penguins)
```

    ## [1] "species"           "island"            "bill_length_mm"   
    ## [4] "bill_depth_mm"     "flipper_length_mm" "body_mass_g"      
    ## [7] "sex"               "year"

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
mean(penguins$flipper_length_mm, na.rm=TRUE)
```

    ## [1] 200.9152

The dataset has 344 rows and 8 columns. The variables are species of the
penguins, the island they’re located, the length of their bill and
flipper, depth of their bill (all in mm), body mass (in grams), sex and
the study year (2007, 2008 or 2009). There are three species represented
(Adélie, Chinstrap and Gentoo), three islands (Biscoe, Dream and
Torgersen).

The mean flipper length is 200.9 mm.

``` r
ggplot(penguins) + 
  geom_point(aes(x=bill_length_mm, y=flipper_length_mm, color=species))
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8103_hw1_fir2103_files/figure-gfm/unnamed-chunk-4-1.png)<!-- -->

``` r
ggsave("scatterplot_penguins.pdf")
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values (geom_point).

### Problem 2

``` r
new_df <- tibble(
  norm_samp = rnorm(10), 
  norm_samp_pos = norm_samp > 0,
  char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
  factor_vec = factor(c("good", "medium", "bad", "good", "medium", "bad", 
                        "good", "medium", "bad", "good"), levels=3)
)

new_df %>% pull(norm_samp) %>% mean()
```

    ## [1] -0.2934457

``` r
new_df %>% pull(norm_samp_pos) %>% mean()
```

    ## [1] 0.4

``` r
new_df %>% pull(char_vec) %>% mean()
```

    ## Warning in mean.default(.): argument is not numeric or logical: returning NA

    ## [1] NA

``` r
new_df %>% pull(factor_vec) %>% mean()
```

    ## Warning in mean.default(.): argument is not numeric or logical: returning NA

    ## [1] NA

The mean for the random normal sample vector and the logical vector work
(-0.09 and 0.4 respectively). The mean for the character vector and
factor vector come out as NA since they aren’t numeric or logical.

``` r
new_df %>% pull(char_vec) %>% as.numeric() %>% mean()
new_df %>% pull(factor_vec) %>% as.numeric() %>% mean()
```

Both of the means are still NA. For a character vector, it would always
be NA. If the factor vector had numbers that could be coerced from
character to numeric, then it would produce a mean.
